// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agrfuralxfoaeaxzawme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFncmZ1cmFseGZvYWVheHphd21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzM5MjksImV4cCI6MjA1OTI0OTkyOX0.bw1WtAkZe_kLVaX_bJYTk-JjxifJkvQdWgxzkd-aRTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);